### ISSUE TITLE
how i can get good quality ss (i mean bigger size)

### ISSUE THREAD

**Issue by erenemresamur** [cocologics/ShareInspector#9]
generally it returns small image (70*70, 80*80) how can i get big image

**Comment by ole** [comment]
We currently only show a thumbnail to indicate whether `NSItemProvider` provides a preview image. We don't have the option to specify the size of the thumbnail (and I don't think it's necessary).

ShareInspector also doesn't have a button for loading the actual shared item and displaying it e.g. in a QuickLook view. I think this would be a useful feature, but it doesn't exist at the moment.
